"""Seed data for SANDAM - Initial beaches in Catalonia"""

import asyncio
from datetime import datetime

from src.database import async_session_maker, init_db
from src.models import Beach, Tide, FlagColor, WaterQuality, DataStatus


CATALONIA_BEACHES = [
    {
        "name": "Platja de la Barceloneta",
        "region": "Cataluña",
        "latitude": 41.3803,
        "longitude": 2.1898,
        "max_capacity": 15000,
        "current_occupation": 45,
        "water_temp": 22.5,
        "air_temp": 28.0,
        "uv_index": 7,
        "wind_speed": 12.5,
        "wave_height": 0.5,
        "tide": Tide.baja,
        "flag_color": FlagColor.green,
        "jellyfish_present": False,
        "sargasso_level": 0,
        "posidonia_present": False,
        "water_quality": WaterQuality.excellent,
        "has_kiosk": True,
        "has_shade": True,
        "has_showers": True,
        "has_parking": True,
        "has_accessibility": True,
        "has_lifeguard": True,
    },
    {
        "name": "Platja de la Costa Brava",
        "region": "Cataluña",
        "latitude": 41.6869,
        "longitude": 2.8651,
        "max_capacity": 5000,
        "current_occupation": 30,
        "water_temp": 21.0,
        "air_temp": 26.0,
        "uv_index": 6,
        "wind_speed": 8.0,
        "wave_height": 0.8,
        "tide": Tide.baja,
        "flag_color": FlagColor.green,
        "jellyfish_present": False,
        "sargasso_level": 1,
        "posidonia_present": True,
        "water_quality": WaterQuality.excellent,
        "has_kiosk": True,
        "has_shade": True,
        "has_showers": True,
        "has_parking": True,
        "has_accessibility": False,
        "has_lifeguard": True,
    },
    {
        "name": "Platja de la Mar Bella",
        "region": "Cataluña",
        "latitude": 41.4074,
        "longitude": 2.2064,
        "max_capacity": 8000,
        "current_occupation": 55,
        "water_temp": 23.0,
        "air_temp": 29.0,
        "uv_index": 7,
        "wind_speed": 10.0,
        "wave_height": 0.4,
        "tide": Tide.media,
        "flag_color": FlagColor.green,
        "jellyfish_present": False,
        "sargasso_level": 0,
        "posidonia_present": False,
        "water_quality": WaterQuality.excellent,
        "has_kiosk": True,
        "has_shade": True,
        "has_showers": True,
        "has_parking": False,
        "has_accessibility": True,
        "has_lifeguard": True,
    },
    {
        "name": "Cala Montjoi - Roses",
        "region": "Cataluña",
        "latitude": 42.2589,
        "longitude": 3.1867,
        "max_capacity": 2000,
        "current_occupation": 25,
        "water_temp": 20.5,
        "air_temp": 25.0,
        "uv_index": 5,
        "wind_speed": 15.0,
        "wave_height": 1.2,
        "tide": Tide.alta,
        "flag_color": FlagColor.yellow,
        "jellyfish_present": True,
        "jellyfish_species": "Pelagia noctiluca",
        "sargasso_level": 2,
        "posidonia_present": True,
        "water_quality": WaterQuality.good,
        "has_kiosk": True,
        "has_shade": True,
        "has_showers": False,
        "has_parking": True,
        "has_accessibility": False,
        "has_lifeguard": True,
    },
    {
        "name": "Platja de Castelldefels",
        "region": "Cataluña",
        "latitude": 41.0521,
        "longitude": 1.9676,
        "max_capacity": 12000,
        "current_occupation": 75,
        "water_temp": 24.0,
        "air_temp": 30.0,
        "uv_index": 8,
        "wind_speed": 5.0,
        "wave_height": 0.3,
        "tide": Tide.baja,
        "flag_color": FlagColor.green,
        "jellyfish_present": False,
        "sargasso_level": 0,
        "posidonia_present": False,
        "water_quality": WaterQuality.excellent,
        "has_kiosk": True,
        "has_shade": True,
        "has_showers": True,
        "has_parking": True,
        "has_accessibility": True,
        "has_lifeguard": True,
    },
    {
        "name": "Platja de Cambrils",
        "region": "Cataluña",
        "latitude": 41.0689,
        "longitude": 1.0522,
        "max_capacity": 10000,
        "current_occupation": 60,
        "water_temp": 23.5,
        "air_temp": 29.0,
        "uv_index": 7,
        "wind_speed": 8.0,
        "wave_height": 0.5,
        "tide": Tide.baja,
        "flag_color": FlagColor.green,
        "jellyfish_present": False,
        "sargasso_level": 1,
        "posidonia_present": False,
        "water_quality": WaterQuality.excellent,
        "has_kiosk": True,
        "has_shade": True,
        "has_showers": True,
        "has_parking": True,
        "has_accessibility": True,
        "has_lifeguard": True,
    },
    {
        "name": "Platja de la Fontsanta - Salou",
        "region": "Cataluña",
        "latitude": 41.0762,
        "longitude": 1.1366,
        "max_capacity": 8000,
        "current_occupation": 85,
        "water_temp": 24.0,
        "air_temp": 30.0,
        "uv_index": 8,
        "wind_speed": 6.0,
        "wave_height": 0.4,
        "tide": Tide.baja,
        "flag_color": FlagColor.yellow,
        "jellyfish_present": False,
        "sargasso_level": 0,
        "posidonia_present": False,
        "water_quality": WaterQuality.good,
        "has_kiosk": True,
        "has_shade": True,
        "has_showers": True,
        "has_parking": True,
        "has_accessibility": True,
        "has_lifeguard": True,
    },
    {
        "name": "Platja de Coma-ruga",
        "region": "Cataluña",
        "latitude": 41.2221,
        "longitude": 1.5612,
        "max_capacity": 6000,
        "current_occupation": 40,
        "water_temp": 22.0,
        "air_temp": 27.0,
        "uv_index": 6,
        "wind_speed": 12.0,
        "wave_height": 0.6,
        "tide": Tide.media,
        "flag_color": FlagColor.green,
        "jellyfish_present": False,
        "sargasso_level": 1,
        "posidonia_present": False,
        "water_quality": WaterQuality.excellent,
        "has_kiosk": True,
        "has_shade": True,
        "has_showers": True,
        "has_parking": True,
        "has_accessibility": True,
        "has_lifeguard": True,
    },
    {
        "name": "Platja de Badalona",
        "region": "Cataluña",
        "latitude": 41.4456,
        "longitude": 2.2471,
        "max_capacity": 7000,
        "current_occupation": 50,
        "water_temp": 22.5,
        "air_temp": 28.0,
        "uv_index": 7,
        "wind_speed": 10.0,
        "wave_height": 0.5,
        "tide": Tide.baja,
        "flag_color": FlagColor.green,
        "jellyfish_present": False,
        "sargasso_level": 0,
        "posidonia_present": False,
        "water_quality": WaterQuality.excellent,
        "has_kiosk": True,
        "has_shade": True,
        "has_showers": True,
        "has_parking": True,
        "has_accessibility": True,
        "has_lifeguard": True,
    },
    {
        "name": "Platja de Sant Pol de Mar",
        "region": "Cataluña",
        "latitude": 41.6025,
        "longitude": 2.6253,
        "max_capacity": 3000,
        "current_occupation": 20,
        "water_temp": 21.0,
        "air_temp": 26.0,
        "uv_index": 5,
        "wind_speed": 8.0,
        "wave_height": 0.7,
        "tide": Tide.alta,
        "flag_color": FlagColor.green,
        "jellyfish_present": False,
        "sargasso_level": 1,
        "posidonia_present": True,
        "water_quality": WaterQuality.excellent,
        "has_kiosk": True,
        "has_shade": True,
        "has_showers": True,
        "has_parking": True,
        "has_accessibility": False,
        "has_lifeguard": True,
    },
]


async def seed_database():
    await init_db()

    async with async_session_maker() as session:
        for beach_data in CATALONIA_BEACHES:
            beach = Beach(**beach_data)
            beach.data_status = DataStatus.live
            beach.created_at = datetime.utcnow()
            beach.last_updated = datetime.utcnow()
            session.add(beach)

        await session.commit()

    print(f"✅ Seeded {len(CATALONIA_BEACHES)} beaches to database")


if __name__ == "__main__":
    asyncio.run(seed_database())